### ISSUE TITLE
My email address is visible on the roster (I attended SB Hacks)

### ISSUE THREAD

**Issue by Windows81** [sbhacks/sbhacksvi-site#12]
Most of the JSON files in [this folder](https://github.com/sbhacks/sbhacksvi-site/tree/abe107fcf53bd4b0ac825e3bc7543e910019a3a5/src/mailer) included are supposedly email lists of the approved applicants for SB Hacks VI.  I find that a bit problematic considering that there are some people out there who wouldn't agree to having their email published on GitHub.

Additionally, this could open up opportunities for telemarketers to target these email addresses for programming-related advertisements.

**Comment by sbhacks** [comment]
Good catch! I removed the JSON email files from the git repo history. Thanks for letting me know.
